### ISSUE TITLE
createColadaUtils rejects router with $route procedures returning Response (regression in v0.53.4)

### ISSUE THREAD

**Issue by productdevbook** [productdevbook/silgi#29]
After upgrading from `v0.53.3` to `v0.53.4`, `createColadaUtils(client)` (re-exported as `createRouterUtils`) fails to type-check on routers that contain `$route` procedures returning a raw `Response`. The same code compiled without issues on `v0.53.3`.

## Repro

A router exposes both a normal RPC tree and a browser-redirect `$route` procedure:

```ts
// server/router.ts
const oauthCallback = s
  .$route({ method: 'GET', path: '/api/oauth/callback' })
  .$resolve(async () => new Response(null, { status: 302, headers: { Location: '/' } }))

const router = {
  storefrontOauthCallback: oauthCallback, // returns Promise<Response>
  api: {
    health: s.$resolve(() => ({ status: 'ok' })),
    // ... regular RPC tree
  },
}
export type AppRouter = typeof router
```

```ts
// client.ts
import { createClient } from 'silgi/client'
import { createLink } from 'silgi/client/misina' // same with /ofetch
import { createColadaUtils } from 'silgi/pinia-colada'
import type { AppRouter } from './server/router'

const client = createClient<AppRouter>(createLink({ url: '/' }))

// ✅ works
export const rpc = client.api

// ❌ TS2345 on v0.53.4 (worked on v0.53.3)
export const api = createColadaUtils(client).api
```

## Error

```
error TS2345: Argument of type '{
  storefrontOauthCallback: () => Promise<Response>;
  api: { health: () => Promise<{...}>; ... }
}' is not assignable to parameter of type 'NestedClient'.

error TS2339: Property 'api' does not exist on type
'(ProcedureUtils<...> & GeneralUtils<...>) | ... | ({ ... } & GeneralUtils<...>)'.
```

The `NestedClient` constraint apparently rejects any sub-tree where a leaf procedure returns `Response` (which is what `$route` procedures legitimately do for browser redirects / OAuth callbacks), poisoning the whole router for `createColadaUtils`.

## Workaround

Scoping to a sub-tree without `$route` procedures (`createColadaUtils(client.api)`) helps somewhat, but that sub-tree itself can still trip `NestedClient` if any nested procedure returns a non-JSON-serializable value, and the resulting `.api` property access then fails.

## Expected

`createColadaUtils` (a.k.a. `createRouterUtils`) should either:

1. accept routers that mix RPC + `$route` procedures (skip / pass-through `$route` leaves, since they are never callable through pinia-colada anyway), or
2. document the constraint and provide an officially supported way to filter `$route` procedures out of the inferred client type.

## Versions

- `silgi`: bumped from `^0.53.3` → `^0.53.4`
- TypeScript: `~6.0.2`
- Link adapter: tested with both `silgi/client/misina` and `silgi/client/ofetch` — same error
- Same source code; only changing the silgi minor reproduces the regression

**Comment by productdevbook** [comment]
Thanks for the detailed write-up. I tried to reproduce locally and a few things don't quite line up — could you help close the gap?

### What I checked

- **Diff between `v0.53.3` and `v0.53.4`.** `git diff v0.53.3..v0.53.4` only touches `src/client/adapters/misina/**`, `lib/misina.*`, `docs/`, `package.json`, `pnpm-lock.yaml`, `tsdown.config.ts`. None of the type-relevant files moved:
  - `src/client/types.ts` (`NestedClient`, `Client`, `ClientRest`)
  - `src/types.ts` (`InferClient`)
  - `src/integrations/pinia-colada/router-utils.ts` (`RouterUtils`, `createRouterUtils`)

  So if this is a genuine regression *between those two tags*, it's not coming from a source change — it would have to be a transitive package or a published-artifact difference. Worth double-checking that the failure really started exactly at `0.53.4` and not earlier (e.g. with the `~6.0.2` TS bump).

- **Reproduction.** I added the exact snippet from your repro (mixed `$route` + RPC tree, `createClient<AppRouter>(createLink({ url: '/' }))`, `createColadaUtils(client).api`) into `test/integrations/pinia-colada.test.ts` and ran it through:
  - `tsgo` (the project's `pnpm typecheck`)
  - stock `typescript@6.0.3` (matches your `~6.0.2`)

  Both pass. No `TS2345` on `createColadaUtils(client)`, no `TS2339` on `.api`. So whatever's tripping your build isn't reproducing from source alone.

### Could you share a minimal repro?

To move this forward, a small standalone repo or a stackblitz that reproduces would help a lot. Specifically:

1. **Exact `package.json`** — `silgi`, `typescript`, `@pinia/colada`, `vue`, `zod`, plus anything else relevant. Ideally a lockfile too, since this might be transitive.
2. **`tsconfig.json`** you're compiling against (the error mentions `~6.0.2`, but flags like `strict`, `exactOptionalPropertyTypes`, `noUncheckedIndexedAccess`, `moduleResolution` matter).
3. **Whether the failure reproduces with both `silgi/client/misina` *and* `silgi/client/ofetch`** — you mentioned both, but a single-link repro is easier to bisect.
4. **What happens on `0.53.3` vs `0.53.4` with the exact same `pnpm-lock.yaml`/`package-lock.json`.** If you only bump `silgi` and nothing else moves, the regression is real and we can bisect; if other deps shifted (e.g. a TS minor), that points elsewhere.

A couple of side-checks that might surface it faster:

- **Is `silgi` resolving from `dist/` or from a workspace?** Mixed resolution (e.g. `dist/index.d.mts` for one import, source for another) sometimes produces this exact "phantom NestedClient mismatch."
- **Does `typeof router` itself look right?** Hover over `router` in your editor and confirm `storefrontOauthCallback` is typed as `ProcedureDef<'query', undefined, Response, {}>` (not `any`, not a builder). If `$route(...).$resolve(...)` is returning the builder instead of the def, `InferClient<typeof router>` would collapse and trip exactly the errors you're seeing.

### About your two suggestions

Both are reasonable and I can do them once we've confirmed the repro:

1. **Skip `$route` leaves in `createColadaUtils`** — doable, but I'd rather understand *why* the constraint is rejecting first; pinia-colada has no special knowledge of `$route` today, so we'd be carving out a new contract.
2. **Document + provide an opt-out** — easy win regardless of (1); I'll likely add this either way once we know the trigger.

If a minimal repro is awkward to share publicly, a private gist or a zip works too.

**Comment by productdevbook** [comment]
Thanks for the careful follow-up — running through your checklist now.

## tsgo (same build as yours): also fails

Our project uses `golar` for typecheck, but I confirmed the failure is **not** golar-specific. Running `@typescript/native-preview@7.0.0-dev.20260417.1` (i.e. `tsgo --noEmit`) directly on our `apps/panel`:

```
src/lib/rpc.ts(69,38): error TS2345: Argument of type '{
  storefrontOauthCallback: () => Promise<Response>;
  api: { health: () => Promise<{...}>; ...; aiAssistant: ...; commerce: ...; pim: ...; ... 16 more }
}' is not assignable to parameter of type 'NestedClient'.

src/lib/rpc.ts(69,46): error TS2339: Property 'api' does not exist on type
  '(ProcedureUtils<ClientContext, any, any, any> & GeneralUtils<any>)
   | (ProcedureUtils<ClientContext, any, AsyncIterableIterator<any>, unknown> & GeneralUtils<...>)
   | ({...} & GeneralUtils<...>)'.
```

So same TS engine, same version — fail.

## silgi resolution: clean (`dist/`, single version)

```
$ pnpm why silgi
silgi 0.53.4
└─ resolves from node_modules/.pnpm/silgi@0.53.4

Found 1 version of silgi
```

No workspace mixing, no source-vs-dist split.

## `typeof oauthCallback` looks correct

In `apps/panel`, hovering `AppRouter['storefrontOauthCallback']`:

```ts
ProcedureDef<"query", undefined, Response, {}>
```

So `$route(...).$resolve(...)` is producing the right `ProcedureDef` — not collapsing to `any` or to the builder. The error message itself confirms `InferClient` is then producing `() => Promise<Response>`, which is exactly what the docs would suggest.

## Minimal repro: cannot reproduce ❌

I built a standalone project mirroring the pattern (full `package.json`, `tsconfig.json`, single-link `silgi/client/misina`):

```ts
// server.ts
export const s = silgi({ wraps: [], context: async (req: Request) => ({ headers: Object.fromEntries(req.headers), /* + several fields */ }) })

const oauthCallback = s
  .$route({ method: 'GET', path: '/api/oauth/callback', summary: 'OAuth callback' })
  .$resolve(async () => new Response(null, { status: 302, headers: { Location: '/' } }))

export const appRouter = s.router({
  ...{ storefrontOauthCallback: oauthCallback },
  api: { ...{ health, users: { list: usersList } } },
})
export type AppRouter = typeof appRouter
```

```ts
// client.ts
const client = createClient<AppRouter>(createLink({ url: '/' }))
export const api = createColadaUtils(client).api  // ✅ no error
```

**Compiles clean** with `tsgo` and stock `typescript@6.0.3`. Same versions, same `silgi@0.53.4`, same `tsconfig` flags (`strict: true`, `moduleResolution: "bundler"`, `target: "ES2023"`).

So the regression **only manifests in the real project**, not in a stripped-down repro. That points at scale or a specific shape we haven't captured yet.

## What the real router has that the minimal repro doesn't

The actual `appRouter` aggregates **9 platform packages** plus core:

```ts
export const appRouter = s.router({
  ...customPathRoutes,           // { storefrontOauthCallback }
  api: {
    health, docFeedback, inngest: { handler }, auth: { handler },
    realtime, setup, identity: { ...8 sub-routers },
    admin, platforms,
    aiAssistant: { ...aiAssistantRoutes, feedback: aiFeedbackRoutes },
    pim: pimRoutes,         // own nested router from another workspace pkg
    commerce: commerceRoutes,
    warehouse: warehouseRoutesGroup,
    hrm: hrmRoutes,
    delivery: deliveryRoutes,
    billing: billingRoutes,
    uploads: uploadRoutes,
    media: mediaRoutes,
    sync: syncRoutes,
  },
})
```

Each `*Routes` import is itself a substantial RPC tree from a separate workspace package. The error message truncates at `... 16 more` keys at the top of `api`, with each value being a nested router tens of procedures deep.

## Hypotheses

1. **Inference budget** — at a certain depth/width, TS gives up resolving the recursive `NestedClient` constraint and falls back to a shape that fails the constraint (the `(ProcedureUtils & GeneralUtils) | ... | ({...} & GeneralUtils)` union in the second error suggests `RouterUtils<T>` distributed over a too-eagerly-evaluated shape).
2. **Cross-package source resolution** — each `*Routes` is exported as `typeof routes` from a workspace `.ts` file (not built `.d.ts`). The `oauthCallback` import is similarly source-form via `@sayfa/commerce/storefront/oauth-callback.api`. If one of the workspace packages is somehow producing a procedure type that *almost* matches `Client<...>` but not exactly, it could poison the `RouterUtils<T>` conditional and select the wrong branch.
3. **Some specific procedure shape** further down the tree (not `$route`) interacts badly with `NestedClient`. The error message starts pointing at `storefrontOauthCallback` but that may just be the first key — the actual offender could be elsewhere.

## What would help next

- Is there a known limit/depth on `NestedClient`/`RouterUtils` recursion in the current implementation?
- Can `RouterUtils<T>` be made more defensive — e.g. wrap the `T extends Client<...>` conditional so that it only matches **leaf** callables (rejecting object types that happen to contain a callable child)? Even without specifically skipping `$route`, that change would likely fix this.
- A debug build that logs which key/path causes the `NestedClient` mismatch would let us pinpoint the offender quickly. If you have a tip on how to extract that with a TS-only probe, happy to run it.

Repository is closed-source so I can't share it directly, but I can run any probe/snippet you want and report back. If a private tarball would help, I can arrange that.

**Comment by productdevbook** [comment]
Great forensics — that narrows it down a lot. The second error is the giveaway:

```
'(ProcedureUtils<ClientContext, any, any, any> & GeneralUtils<any>)
 | (ProcedureUtils<ClientContext, any, AsyncIterableIterator<any>, unknown> & GeneralUtils<...>)
 | ({...} & GeneralUtils<...>)'
```

That's `RouterUtils<T>` evaluated against `NestedClient` itself (not your concrete router). When `T extends NestedClient` fails, TS doesn't error out cleanly — it widens `T` to the constraint and then the conditional `T extends Client<...> ? ... : ...` distributes over the union (`Client | SubscriptionClient | { [k]: NestedClient }`), giving you exactly that three-arm union. `.api` doesn't exist on all three, so TS2339 follows.

So the real question is just: **why does the `NestedClient` constraint reject this router shape**, even though `() => Promise<Response>` looks assignable to `Client<C, any, any, any>`?

Two probes that should pinpoint it. Both are pure type-level, no runtime, no shipping changes.

### Probe 1 — find the offending key

Drop this next to your `client = createClient<AppRouter>(...)`:

```ts
import type { NestedClient } from 'silgi/client'
import type { InferClient } from 'silgi'

type FailingKeys<T> = {
  [K in keyof T]: T[K] extends NestedClient ? never : K
}[keyof T]

type _Bad = FailingKeys<InferClient<AppRouter>>
//   ^? hover this — should be `never` if every top-level key is fine
```

If `_Bad` is `never`, recurse one level into `api`:

```ts
type _BadInApi = FailingKeys<InferClient<AppRouter>['api']>
```

Keep drilling until `_Bad` resolves to one or more concrete keys. The offender is almost certainly *not* `storefrontOauthCallback` — the error message lists it first because it's the first key, but TS reports the whole-object mismatch, not the specific failing leaf.

### Probe 2 — confirm `Client<...>` is the failing arm

Once you have a candidate from Probe 1:

```ts
import type { Client, SubscriptionClient } from 'silgi/client'

type _Leaf = InferClient<AppRouter>['<offending-key>']
//   ^? hover

type _IsClient       = _Leaf extends Client<any, any, any, any> ? true : false
type _IsSubscription = _Leaf extends SubscriptionClient<any, any, any> ? true : false
```

If both are `false` but the leaf still looks like a function on hover, we have a bivariance / contextual-context-parameter mismatch and I can fix it in `Client` / `ClientRest`. If `_Leaf` itself looks weird (e.g. an intersection, or `never`, or a `ProcedureDef` that didn't get unwrapped), the workspace source-vs-dist hypothesis is the real cause and the fix is on the resolution side.

### Probe 3 — workspace `silgi` identity

If Probe 2 points to "Client failure," also worth confirming `silgi`'s types are nominally identical across all your workspace packages. From `apps/panel`:

```ts
import type { ProcedureDef as PD_App } from 'silgi'
// pick one workspace package whose router shows up under `api`:
import type { ProcedureDef as PD_Pkg } from '@sayfa/commerce/.../some-file-that-re-exports-it'
// (or just import from the package's `silgi` directly if accessible)

type _SameDef = PD_App extends PD_Pkg ? (PD_Pkg extends PD_App ? true : false) : false
//   ^? hover — must be `true`
```

If that resolves to `false` you have two `silgi` type identities in the graph (different `dist/index.d.mts` instances or one of them resolved from source), and every procedure built with the "other" `silgi` will fail the `Client<C,…>` constraint check on the consumer side.

`pnpm why silgi` showing one version is necessary but not sufficient — TS keys types by *file path*, not version, so two paths to the same `0.53.4` (e.g. `node_modules/.pnpm/silgi@0.53.4/...` vs a hoisted copy somewhere) produce distinct types.

### About a defensive `RouterUtils`

Independent of the above, I think `RouterUtils<T>` is too eager:

```ts
// current
export type RouterUtils<T extends NestedClient> =
  T extends Client<infer UClientContext, infer UInput, infer UOutput, infer UError>
    ? ProcedureUtils<...> & GeneralUtils<UInput>
    : { [K in keyof T]: T[K] extends NestedClient ? RouterUtils<T[K]> : never } & GeneralUtils<unknown>
```

The `T extends Client<...>` check matches **anything callable**, including objects that happen to be callable (like a callable router). Tightening it so the "leaf" arm only matches *pure* functions — not function-with-properties — would also stop the union-distribution blowup in your error and is safe to ship. I can prep that as a follow-up PR once we've confirmed which probe lights up.

Run Probe 1 first and post `_Bad` (and the leaf shape on hover). That alone should be enough to decide between "fix `Client`/`NestedClient`" and "fix workspace resolution."

**Comment by productdevbook** [comment]
🎯 **Found it. The probes nailed the actual offender — and it's not `$route`.**

## Probe 1 — failing keys

```
type _Top = FailingKeys<InferClient<AppRouter>>           // → "api"
type _Api = FailingKeys<InferClient<AppRouter>['api']>    // → "aiAssistant"
```

`storefrontOauthCallback` was a **red herring** — it satisfies `NestedClient` just fine. The error message listed it first only because it's the first key of the failing top-level object. The actual offender is `aiAssistant`, and one level deeper:

```
type _AiAssistant = FailingKeys<InferClient<AppRouter>['api']['aiAssistant']>  // → "chat"
```

## Probe 2 — `chat` shape

```ts
type _Chat = InferClient<AppRouter>['api']['aiAssistant']['chat']
type _IsClient = _Chat extends Client<any, any, any, any> ? true : false  // → false ✅
type _ChatReturn = _Chat extends (...args: any[]) => infer R ? R : never
//   ^? AsyncIterableIterator<{ type: "text-delta"; delta: string } | ... 7 more variants>
```

**`_Chat` is `(input: ...) => AsyncIterableIterator<TOutput>` — i.e. without the `Promise<>` wrapper.** That's the bug.

`SubscriptionClient` is defined as `(...args) => Promise<AsyncIterableIterator<TOutput>>`, so `_Chat` doesn't match `SubscriptionClient`, and it doesn't match `Client` either (`AsyncIterableIterator` is not a `Promise`), so it falls through to the object-branch of `NestedClient`, which then fails because the function value isn't an object of `NestedClient` properties → cascade → the `RouterUtils<T>` distribution your prior comment described.

## Server side: it's a `s.subscription()` procedure

The offending `chat` procedure on the server:

```ts
export const chatRoute = s
  .subscription()
  .$input(chatInput)
  .$output(chatEvent)
  .$resolve(async function* ({ input }) {
    yield /* ChatEvent */
  })
```

So `InferClient` is collapsing `subscription()` + `async function*` into `(...args) => AsyncIterableIterator<T>` instead of `(...args) => Promise<AsyncIterableIterator<T>>`.

## ✅ Standalone minimal repro (now reproduces)

Adding a single `s.subscription()` procedure to the previous "minimal repro that compiled clean" reproduces the exact same error:

```ts
// server.ts
const chatRoute = s
  .subscription()
  .$input(z.object({ message: z.string() }))
  .$resolve(async function* ({ input }) {
    yield { type: 'text-delta' as const, delta: input.message }
    yield { type: 'done' as const }
  })

export const appRouter = s.router({
  api: { chat: chatRoute },
})
```

```ts
// client.ts
const client = createClient<AppRouter>(createLink({ url: '/' }))
export const api = createColadaUtils(client).api
```

```
error TS2345: Argument of type '{ api: { chat: (input: { message: string; }) => AsyncIterableIterator<...>; }; }'
  is not assignable to parameter of type 'NestedClient'.
  ...
  Type 'AsyncIterableIterator<...>' is missing the following properties from type 'Promise<any>':
    then, catch, [Symbol.toStringTag], finally

error TS2339: Property 'api' does not exist on type
  '(ProcedureUtils<ClientContext, any, any, any> & GeneralUtils<any>)
   | (ProcedureUtils<ClientContext, any, AsyncIterableIterator<any>, unknown> & GeneralUtils<...>)
   | ({...} & GeneralUtils<...>)'.
```

Identical to what we see in the real project. So:

- **`$route` had nothing to do with it.** I'll edit the issue title/body to reflect the actual cause.
- The bug is in **`InferClient` for `subscription` procedures**: it should produce `Promise<AsyncIterableIterator<TOutput>>`, but it's producing `AsyncIterableIterator<TOutput>` directly.

## Probe 3 — workspace identity (side note, not the cause)

While drilling I noticed `node_modules/.pnpm/` carries **four** silgi versions on disk:

```
silgi@0.53.0_…
silgi@0.53.2_…
silgi@0.53.3_…
silgi@0.53.4_…
```

…even though `pnpm-lock.yaml` only has `silgi@0.53.4`. They're orphan installs from earlier upgrades (`pnpm` didn't prune). All workspace packages resolve to `0.53.4` at runtime / from TS's perspective (`typeof oauthCallback` and `_Chat` both come from the `0.53.4` `dist/`), so this isn't what's causing the regression — but worth flagging as something to be aware of when chasing similar issues.

## Suggested fix

In `src/types.ts`, `InferClient<T>` for `ProcedureDef<'subscription', ...>` needs to wrap its output:

```ts
type ProcedureResult<TType extends ProcedureType, TOutput> =
  TType extends 'subscription'
    ? Promise<AsyncIterableIterator<TOutput>>   // currently: AsyncIterableIterator<TOutput>
    : Promise<TOutput>
```

…or wherever the subscription-vs-query branching lives. Once that returns a `Promise<…>`, the `Client<C, any, any, any>` arm of `NestedClient` accepts it and the cascade goes away. The defensive `RouterUtils<T>` tightening you suggested is still a good belt-and-suspenders, but the immediate regression is purely in `InferClient`.

Happy to send a PR if helpful — let me know whether you'd like me to take a swing at it or you'd rather own the fix.

**Comment by productdevbook** [comment]
Excellent debugging — that's a clean root cause and the probes did exactly what they were supposed to do.

## Confirming the bug from source

`src/types.ts:159-161`:

```ts
type ProcedureResult<TType extends ProcedureType, TOutput> = TType extends 'subscription'
  ? AsyncIterableIterator<TOutput>          // ← missing Promise wrap
  : Promise<TOutput>
```

Meanwhile `src/client/types.ts:26-28` correctly types the runtime contract:

```ts
export type SubscriptionClient<...> = (
  ...args: ClientRest<TClientContext, TInput>
) => Promise<AsyncIterableIterator<TOutput>>
```

So `ProcedureResult` and `SubscriptionClient` disagree about whether subscriptions are awaited. This is also out of sync with the **actual runtime behavior**:

- `src/client/client.ts:54-55` — `procedureClient = (input, options) => link.call(...)` returns a `Promise` for every procedure (queries, mutations, *and* subscriptions), because `link.call` is `async`.
- `test/client/ws-link.test.ts:63` consumes a subscription with `(await client.ticks()) as AsyncIterableIterator<…>` — confirming the runtime returns `Promise<AsyncIterableIterator<T>>` and the consumer must `await` first.

So the runtime has always been `Promise<AsyncIterableIterator<T>>`. The bug is purely in `InferClient`'s type-level mapping: it strips the `Promise` wrap for subscriptions and produces `() => AsyncIterableIterator<T>` instead, which doesn't match either arm of `NestedClient` and triggers the cascade you traced. That's the regression — and as you noticed, it has nothing to do with `$route` / `Response`.

## The fix

One-line change in `src/types.ts`:

```diff
 type ProcedureResult<TType extends ProcedureType, TOutput> = TType extends 'subscription'
-  ? AsyncIterableIterator<TOutput>
+  ? Promise<AsyncIterableIterator<TOutput>>
   : Promise<TOutput>
```

After this, `InferClient<typeof chatRoute>` becomes `(input) => Promise<AsyncIterableIterator<ChatEvent>>`, which is exactly `SubscriptionClient<ClientContext, …, ChatEvent>`, which is one arm of `NestedClient`. The recursive constraint check resolves cleanly, and the union-distribution fallout in `RouterUtils<T>` disappears.

## Test fallout (intentional + needed)

Two existing tests in `test/core/types.test.ts` currently assert the buggy shape and will need updating:

```ts
// types.test.ts:385  (subscription — returns AsyncIterableIterator)
- expectTypeOf<Client>().toEqualTypeOf<() => AsyncIterableIterator<{ tick: number; time: string }>>()
+ expectTypeOf<Client>().toEqualTypeOf<() => Promise<AsyncIterableIterator<{ tick: number; time: string }>>>()

// types.test.ts:394-396  (subscription with input)
- expectTypeOf<Client>().toEqualTypeOf<
-   (input: { channel: string }) => AsyncIterableIterator<{ channel: string; message: string }>
- >()
+ expectTypeOf<Client>().toEqualTypeOf<
+   (input: { channel: string }) => Promise<AsyncIterableIterator<{ channel: string; message: string }>>
+ >()
```

…and the `stream` branch of the mixed-router test at `types.test.ts:421-424`. The fact that those tests previously locked in the wrong shape is exactly why the regression slipped through — the type-level assertions matched the type-level definition rather than the runtime contract.

I'd add a regression test in `test/integrations/pinia-colada.test.ts` mirroring your minimal repro (router with a `subscription`, then `RouterUtils<InferClient<typeof router>>['key']` must be a function) so this can't regress quietly again.

## Defensive `RouterUtils` — separate, still worth doing

Independent of this fix, the `T extends Client<...>` arm of `RouterUtils` still matches callable objects, which is what produced the union-of-three-arms in your error message instead of a clean diagnostic. Tightening that to "leaf callable only" is a belt-and-suspenders change that gives a much better error next time something falls through `NestedClient`. I'd ship it as a small follow-up after the `Promise` fix lands, not bundled into the same patch.

## On your closed-source repro

Don't worry about it — your standalone repro nails it:

```ts
const chatRoute = s.subscription().$input(z.object({ message: z.string() }))
  .$resolve(async function* ({ input }) { yield {...}; yield {...} })

export const appRouter = s.router({ api: { chat: chatRoute } })
// createColadaUtils(client).api → TS2345 + TS2339
```

That's a 10-line test case. It can go straight into `test/integrations/pinia-colada.test.ts` as the regression guard.

## On the orphan `silgi@0.53.{0,2,3}` in `node_modules/.pnpm/`

`pnpm prune` (or `pnpm install --frozen-lockfile` in CI) should clear those. They're not causing this issue, but yeah — worth tidying so future bisects don't get muddied.

---

I can land this myself: the `ProcedureResult` one-liner, the three test-shape updates in `core/types.test.ts`, and a new regression test in `pinia-colada.test.ts`. Want me to open the PR, or would you prefer to take it?

**Comment by productdevbook** [comment]
🚀 **Confirmed fixed in v0.53.5.**

Bumped from `^0.53.4` → `^0.53.5` across the workspace. Results:

## ✅ All cascading errors gone

- `rpc.ts:69` (`createColadaUtils(client).api`) — clean
- `_shared/ui/ai-actions.ts:20`, `_shared/ui/runtime.ts:29`, `_shared/ui/runtime.ts:16` (the `RouterUtils<T>` distribution at consumer sites) — all clean
- `RouterUtils` constraint resolves correctly now that `InferClient` produces `(input) => Promise<AsyncIterableIterator<T>>` for `subscription` procedures.

## Consumer cleanup we shipped on our side

The bug had bled into our consumer code as a workaround. With v0.53.5 the runtime contract finally matches the type contract, so the workaround came out:

```diff
- // silgi tip sistemi SubscriptionClient'ı doğrudan AsyncIterableIterator olarak
- // işaretliyor ama runtime'da link.call() Promise döner. Hem promise hem
- // iterator destekleyelim — gelecekte silgi düzeltirse de patlamaz.
- export type AssistantClientCall = (input: ChatInput) => AsyncIterableIterator<ChatEvent>
+ export type AssistantClientCall = (input: ChatInput) => Promise<AsyncIterableIterator<ChatEvent>>
```

```diff
- const result = call(input)
- const iterator = (
-   result && typeof (result as { then?: unknown }).then === 'function'
-     ? await (result as unknown as Promise<AsyncIterableIterator<ChatEvent>>)
-     : result
- ) as AsyncIterableIterator<ChatEvent>
+ const iterator = await call(input)
```

Several files of "type says X but runtime gives Y, handle both just in case" code had grown around the buggy `InferClient` shape — all gone now. So the fix has a real cleanup multiplier on consumer codebases too.

## `pnpm prune` clear

After bumping, the orphan `silgi@0.53.{0,2,3}` directories under `node_modules/.pnpm/` are gone (`pnpm install` cleaned them when the lockfile resolved exactly one version). So the workspace is also down to a single silgi identity now.

## On the side note

I noticed `rpc.aiAssistant.feedback.submit.call(input)` (plain mutation, called via `.call`) now flags as `Expected 2 arguments, but got 1` — the silgi proxy's `.call` no longer matches `Function.prototype.call(thisArg, ...args)` semantics on regular procedures. Probably intentional/orthogonal — we just switched to direct call (`feedback.submit(input)`) which is cleaner anyway. Mentioning in case it surprises others mid-upgrade.

Thanks for the lightning-fast turnaround on this — the probes you suggested were exactly the right tools, and the fix is one line. ⭐

This issue can be closed from our side. The defensive `RouterUtils<T>` follow-up you mentioned would still be a nice ergonomic win for future regressions, but the immediate problem is fully resolved.
